[workspace]

members = [
    "geph4-binder",
    "geph4-exit",
    "lib/tundevice",
    "lib/mizaru",
    "lib/binder_transport",
    "lib/smolscale",
    "lib/aioutils",
    "lib/vpn_structs",
    "lib/socks2http-rs",
    "lib/sosistab",
    "lib/warpfront",
    "lib/spiderchan",
    "geph4-vpn-helper",
    "geph4-client",
    "geph4-bridge"
] 


[profile.dev]
opt-level=2
lto="off"
# panic = "abort" 
incremental=true

[profile.release]
panic = "abort"
opt-level=3
debug=1

[patch.crates-io]
async-executor={git="https://github.com/geph-official/async-executor.git", branch="local-queues"}
# async-executor={path="../async-executor"}
