[workspace]

members = [
    "geph4-binder",
    "geph4-exit",
    "lib/tundevice",
    "lib/mizaru",
    "lib/binder_transport",
    "lib/smolscale",
    "lib/aioutils",
    "lib/vpn_structs",
    "lib/sosistab",
    "lib/warpfront",
    "geph4-vpn-helper",
    "geph4-client",
    "geph4-bridge"
] 


[profile.dev]
opt-level=2
lto="off"
incremental=true

[profile.release]
panic = "abort"
opt-level=3
