[workspace]

members = [
    "geph4-binder",
    "geph4-exit",
    "lib/tundevice",
    "lib/mizaru",
    "lib/binder_transport",
    "lib/smolscale",
    "lib/sosistab",
    "geph4-client",
    "geph4-bridge"
] 


[profile.dev]
opt-level=2
lto="off"

[profile.release]
panic = "abort"
opt-level=3
incremental=true
lto="thin"