[package]
name = "geph4-binder"
version = "0.1.0"
authors = ["geph-official"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.17.5"
anyhow = "1.0.32"
libsodium-sys = "0.2.6"
binder_transport = {path="../lib/binder_transport"}