# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/rust:1.46.0
    steps:
      - checkout:
          path: ~/repo
      - run: rustup target add x86_64-unknown-linux-musl
      - run: cargo build --release --target x86_64-unknown-linux-musl --manifest-path=geph4-client/Cargo.toml
      - run: cargo install cross
      - run: CROSS_DOCKER_IN_DOCKER=true cross build --release --target armv7-unknown-linux-musleabihf --manifest-path=geph4-client/Cargo.toml
      - store_artifacts:
          path: ~/repo/target/
