# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
jobs:
  build:
    working_directory: ~/repo/
    machine:
      image: ubuntu-2004:202008-01
    resource_class: 2xlarge
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
      - run: echo "export RUSTFLAGS='-C link-arg=-s'" >> $BASH_ENV
      - run: sh osx_build.sh
      - run: cargo install cross
      - run: cross build --release --target x86_64-pc-windows-gnu --manifest-path=geph4-client/Cargo.toml && cross build --release --target x86_64-unknown-linux-musl --manifest-path=geph4-client/Cargo.toml && cross build --release --target armv7-linux-androideabi --manifest-path=geph4-client/Cargo.toml && cross build --release --target aarch64-linux-android --manifest-path=geph4-client/Cargo.toml
      - run: cross build --release --target x86_64-unknown-linux-musl --manifest-path=geph4-bridge/Cargo.toml
      - run: mkdir ~/repo/OUTPUT/
      - run: mv ~/repo/target/x86_64-unknown-linux-musl/release/geph4-client ~/repo/OUTPUT/geph4-client-linux-amd64
      - run: mv ~/repo/target/x86_64-unknown-linux-musl/release/geph4-bridge ~/repo/OUTPUT/geph4-bridge-linux-amd64
      - run: mv ~/repo/target/armv7-linux-androideabi/release/geph4-client ~/repo/OUTPUT/geph4-client-android-armv7
      - run: mv ~/repo/target/aarch64-linux-android/release/geph4-client ~/repo/OUTPUT/geph4-client-android-aarch64
      - run: mv ~/repo/target/x86_64-pc-windows-gnu/release/geph4-client.exe ~/repo/OUTPUT/geph4-client-windows-amd64.exe
      - run: mv ~/repo/target/x86_64-apple-darwin/release/geph4-client ~/repo/OUTPUT/geph4-client-macos-amd64
      - run: sudo apt install python3-pip
      - run: sudo pip3 install --upgrade b2
      - run: |
          b2 authorize-account $B2_KEYID $B2_APPKEY
      - run: b2 sync ~/repo/OUTPUT/ b2://geph-dl/geph4-binaries/
