# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
jobs:
  build:
    working_directory: ~/repo/
    machine:
      image: ubuntu-1604:202007-01
    resource_class: xlarge
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install upx-ucl
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
      - run: echo "export RUSTFLAGS='-C link-arg=-s'" >> $BASH_ENV
      - run: cargo install cross
      - run: cross build --release --target x86_64-unknown-linux-musl --manifest-path=geph4-client/Cargo.toml
      - run: cross build --release --target arm-unknown-linux-musleabi --manifest-path=geph4-client/Cargo.toml
      - run: cross build --release --target aarch64-unknown-linux-musl --manifest-path=geph4-client/Cargo.toml
      - run: mkdir ~/repo/OUTPUT/
      - run: mv ~/repo/target/x86_64-unknown-linux-musl/release/geph4-client ~/repo/OUTPUT/geph4-client-linux-amd64
      - run: mv ~/repo/target/arm-unknown-linux-musleabi/release/geph4-client ~/repo/OUTPUT/geph4-client-linux-armeabi
      - run: mv ~/repo/target/aarch64-unknown-linux-musleabi/release/geph4-client ~/repo/OUTPUT/geph4-client-linux-aarch64
      - run: upx OUTPUT/*
      - store_artifacts:
          path: ~/repo/OUTPUT
