# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# Orchestrate or schedule a set of jobs
jobs:
  build:
    working_directory: ~/repo/
    machine:
      image: ubuntu-2004:202008-01
    resource_class: 2xlarge
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
      - run: echo "export RUSTFLAGS='-C link-arg=-s'" >> $BASH_ENV
      - run: cargo install cross
      - run: sh all_build.sh
      - run: sudo apt install python3-pip
      - run: sudo pip3 install --upgrade b2
      - run: |
          b2 authorize-account $B2_KEYID $B2_APPKEY
      - run: b2 sync ~/repo/OUTPUT/ b2://geph-dl/geph4-binaries/
