[package]
name = "geph4-client"
version = "0.0.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"
async-h1= "2.1.3"
bincode = "1.3.1"
binder_transport = {path="../lib/binder_transport"}
cap= "0.1.0"
dirs = "3.0.1"
ed25519-dalek={ version = "1.0.1", features = ["serde"] }
flexi_logger = "0.16.1"
futures-lite= "1.11.1"
hex = "0.4.2"
tar="0.4"
http-types = "2.6.0"
log = "0.4.11"
mizaru={path="../lib/mizaru"}
once_cell= "1.4.1"
parking_lot = { version = "0.11.0", features = ["serde"] }
rand= "0.7.3"
regex= "1.4.1"
rsa-fdh = "0.4.1"
rusqlite={ version = "0.24.1", features = ["bundled" ] }
scopeguard = "1.1.0"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
sha2 = "0.9.1"
smol = "1.2.4"
smol-timeout = "0.6.0"
socksv5 = "0.2.0"
sosistab={path="../lib/sosistab"}
strsim = "0.10.0"
structopt = "0.3.20"
x25519-dalek={ version = "1.1.0", features = ["serde"] }
chrono = "0.4.19"
num_cpus= "1.13.0"


[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
jemallocator-global = "0.3.0"